# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55736373641b7f74994b72e56774b53755fe4c312b33b1a2623747a932203894734416dc1aea55b3784afe5cf266cebd58df423fbef8a2e9183a039f1d4a6924

test:
  secret_key_base: b357f798ae0711e621e2c4be36ab6aaccc7cbb1847f3b5852102e1e69562bea5b0349674394c44c4b01ff60fe4337c2f532fb0ac2a646f9e2a352bfed5cc2ee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
